apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    env:
      ACTION_ID: "cloudbees-io/helm-package"
      SERVICE_REPO: "calculi-corp/run-service"
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: "${{ env.SERVICE_REPO }}"
      - name: Print hello
        uses: docker://alpine:3.18
        shell: sh
        run: |
          echo "hello from workflow"