apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: "calculi-corp/run-service"

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo ls -l
