apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v2
        with:
          repository: "calculi-corp/run-service"

      - name: Configure git credentials
        uses: cloudbees-io/configure-git-global-credentials@v2

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo ls -l
