apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    env:
      ACTION_ID: "cloudbees-io/helm-package"
      SERVICE_REPO: "calculi-corp/run-service"
      TICKET_NUMBER: "CBP-1234"
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: "${{ env.SERVICE_REPO }}"
      - name: Run shell commands
        uses: docker://alpine:3.18
        shell: sh
        run: |
          echo "hello from workflow"
          set -eu
          mkdir -p "$TICKET_NUMBER"

          # Determine service directory. If checkout used 'path', set CHECKOUT_PATH env accordingly.
          SERVICE_DIR="${CHECKOUT_PATH:-$(basename "$SERVICE_REPO")}";

          # If the computed dir doesn't exist, try to find the checked-out repo directory.
          if [ ! -d "$SERVICE_DIR" ]; then
            echo "Service dir '$SERVICE_DIR' not found; searching for repo dir..."
            SERVICE_DIR=$(find . -maxdepth 3 -type d -name "$(basename "$SERVICE_REPO")" -print -quit || true)
          fi

          if [ -z "$SERVICE_DIR" ] || [ ! -d "$SERVICE_DIR" ]; then
            echo "ERROR: service checkout directory not found for '$SERVICE_REPO'" >&2
            ls -la || true
            exit 1
          fi

          echo "Moving '$SERVICE_DIR' to '$TICKET_NUMBER/'"
          mv "$SERVICE_DIR" "$TICKET_NUMBER/"
          