apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    env:
      ACTION_ID: "cloudbees-io/helm-package"
      SERVICE_REPO: "calculi-corp/run-service"
      TICKET_NUMBER: "CBP-1234"
      CHECKOUT_PATH: "service"
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: "${{ env.SERVICE_REPO }}"

      - name: Run shell commands
        uses: docker://alpine:3.18
        shell: sh
        run: |
          set -eu
          SERVICE_DIR="${CHECKOUT_PATH:-$(basename "$SERVICE_REPO")}" 
          echo "Looking for checked-out directory: $SERVICE_DIR"
          if [ -d "$SERVICE_DIR" ]; then
            ls -la "$SERVICE_DIR"
          else
            echo "Service directory '$SERVICE_DIR' not found; listing workspace:" >&2
            ls -la
          fi
          echo "hello from workflow"
