apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    env:
      ACTION_ID: "cloudbees-io/helm-package"
      SERVICE_REPO: "calculi-corp/run-service"
    steps:
      - name: Checkout repository
        uses: cloudbees-io/checkout@v1
        with:
          repository: "${{ env.SERVICE_REPO }}"

      - name: Run action update script
        uses: docker://golang:1.20.3
        shell: bash
        run: |
          chmod +x ./test_any_action_main_branch_in_service.sh
          ./test_any_action_main_branch_in_service.sh -a "$ACTION_ID"
